<a href="https://colab.research.google.com/github/anaustinbeing/neural-networks/blob/main/perceptron_and_adalinegd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simple Perceptron Model and Adaptive Linear Neuron classifier

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('inputpixels_training.csv', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,-1,-1,1,1,-1,-1,-1,-1,-1,-1,...,1,-1,1,1,1,-1,1,1,1,1
1,1,1,1,1,1,1,-1,-1,1,-1,...,-1,1,1,1,1,1,1,1,-1,-1
2,-1,-1,1,1,1,1,1,-1,1,-1,...,-1,1,-1,-1,1,1,1,1,-1,-1
3,1,1,1,1,1,-1,-1,-1,1,-1,...,1,-1,1,1,1,1,1,-1,-1,-1
4,1,1,1,1,1,1,1,-1,1,-1,...,-1,1,1,1,1,1,1,1,1,-1
5,-1,-1,-1,1,1,1,1,-1,-1,-1,...,1,-1,-1,-1,1,1,1,-1,-1,-1
6,-1,1,-1,1,1,1,1,-1,-1,-1,...,1,-1,-1,-1,1,1,-1,-1,-1,-1
7,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,1,-1,-1,1,-1,-1,-1,1,-1,1
8,1,1,1,1,1,1,-1,1,-1,-1,...,-1,1,1,1,1,1,1,1,-1,-1
9,-1,-1,1,1,1,-1,-1,-1,1,-1,...,-1,1,-1,-1,1,1,1,-1,-1,-1
10,1,1,1,1,1,-1,-1,1,-1,-1,...,1,-1,1,1,1,1,1,-1,-1,-1
11,1,1,1,1,1,1,1,1,-1,-1,...,-1,1,1,1,1,1,1,1,1,-1
12,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,...,1,-1,-1,-1,1,1,1,-1,-1,-1
13,-1,1,-1,1,1,1,1,-1,-1,-1,...,1,-1,-1,-1,1,1,-1,-1,-1,-1
14,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,1,-1,-1,-1,1,1,1
15,1,1,1,1,1,1,-1,-1,1,-1,...,-1,1,1,1,1,1,1,1,-1,-1
16,-1,-1,1,1,1,-1,1,-1,1,-1,...,-1,1,-1,-1,1,1,1,-1,-1,-1
17,1,1,1,1,1,-1,-1,-1,1,-1,...,1,-1,1,1,1,1,1,-1,-1,-1
18,1,1,1,1,1,1,1,-1,1,-1,...,-1,1,1,1,1,1,1,1,1,-1
19,-1,-1,-1,-1,1,1,1,-1,-1,-1,...,1,-1,-1,-1,1,1,1,-1,-1,-1
20,-1,1,1,1,1,1,1,-1,-1,-1,...,1,-1,-1,1,1,1,-1,-1,1,-1

In [ ]:
x_train, y_train = df.iloc[:, :-1], df.iloc[:, -1]
print(x_train.shape, y_train.shape)

(21, 63) (21,)

### Perceptron Model (Method 1: Using built-ins)

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

perceptron = Perceptron(eta0=0.1, random_state=1)
perceptron.fit(x_train, y_train)

Perceptron(eta0=0.1, random_state=1)

In [ ]:
df_test = pd.read_csv('inputpixels_testing.csv', header=None)
df_test

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,1,1,1,1,1,1,1,1,1,-1
1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,1,-1,-1,1,-1,-1,-1,1,-1,1
2,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,1,-1,-1,-1,1,1,1
3,1,1,1,1,1,1,-1,-1,1,-1,...,-1,1,1,1,1,1,1,1,-1,-1
4,-1,-1,1,1,1,-1,1,-1,1,-1,...,-1,1,-1,-1,1,1,1,-1,-1,-1
5,1,1,1,1,1,-1,-1,-1,1,-1,...,1,-1,1,1,1,1,1,-1,-1,-1
6,1,1,1,1,1,1,1,-1,1,-1,...,-1,1,1,1,1,1,1,1,1,-1
7,-1,-1,-1,-1,1,1,1,-1,-1,-1,...,1,-1,-1,-1,1,1,1,-1,-1,-1
8,-1,1,1,1,1,1,1,-1,-1,-1,...,1,-1,-1,1,1,1,-1,-1,1,-1

In [ ]:
x_test, y_test = df_test.iloc[:, :-1], df_test.iloc[:, -1]
print(x_test.shape, y_test.shape)

(9, 63) (9,)

In [ ]:
for index, row in x_test.iterrows():
  y_pred = perceptron.predict([row])
  print(y_pred, y_test.iloc[index])
  print('Accuracy: %.3f' % accuracy_score([y_test.iloc[index]], y_pred))

[1] -1
Accuracy: 0.000
[1] 1
Accuracy: 1.000
[1] 1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000
[-1] -1
Accuracy: 1.000

### Perceptron Model (Method 2)

In [ ]:
class MyPerceptron:

  def __init__(self, n_inputs):
    self.weights = np.zeros(n_inputs)
    self.bias = 0.0
  
  def predict(self, x):
    weighted = np.sum(np.dot(x, self.weights)) + self.bias
    # print(weighted)
    if weighted > 0:
      return 1
    else:
      return -1
    
  def train(self, x, y):
    predicted_value = self.predict(x)
    if predicted_value != y:
      difference = y - predicted_value
      for i in range(len(self.weights)):
        self.weights[i] += difference * x[i]
      self.bias += difference

# creating perceptron
my_perceptron = MyPerceptron(63)

# training
for index, features in x_train.iterrows():
  my_perceptron.train(features, y_train.iloc[index])

# testing
for index, row in x_test.iterrows():
  y_pred = my_perceptron.predict([row])
  print('Actual: ', y_test.iloc[index], ' Predicted: ', y_pred)
  print('Accuracy: %.3f' % accuracy_score([y_test.iloc[index]], [y_pred]))

Actual:  -1  Predicted:  1
Accuracy: 0.000
Actual:  1  Predicted:  1
Accuracy: 1.000
Actual:  1  Predicted:  1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000
Actual:  -1  Predicted:  -1
Accuracy: 1.000

### Adaptive Linear Neuron classifier

In [ ]:
import numpy as np

class AdalineGD(object):
    """ADAptive LInear NEuron classifier.

    Parameters
    ------------
    eta : float
        Learning rate (between 0.0 and 1.0)
    n_iter : int
        Passes over the training dataset.

    Attributes
    -----------
    w_ : 1d-array
        Weights after fitting.
    cost_ : list
        SSE in every epoch.

    """
    def __init__(self, eta=0.01, n_iter=500):
        self.eta = eta
        self.n_iter = n_iter
    
    def fit(self, X, y):
        """ Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_samples, n_features]
            Training vectors, where n_samples is the number of samples and
            n_features is the number of features.
        y : array-like, shape = [n_samples]
            Target values.

        Returns
        -------
        self : object

        """
        self.w_ = np.zeros(X.shape[1] + 1)
        self.cost_ = []
        
        for i in range(self.n_iter):
            # calculating wTx
            output = self.net_input(X)

            # calculating errors
            errors = y - output
            
            # calculating weight update
            self.w_[1:] += self.eta * X.T.dot(errors)
            self.w_[0] += self.eta * errors.sum()
            
            # calculating cost
            cost = (errors**2).sum() / 2.0
            self.cost_.append(cost)
        return self
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]
    
    def activation(self, X):
        return self.net_input(X)
        
    def predict(self, X):
        return np.where(self.activation(X) >= 0.0, 1, -1)

In [ ]:
df = pd.read_csv('inputpixels_training.csv', header=None)
x_train, y_train = df.iloc[:, :-1].to_numpy(), df.iloc[:, -1].to_numpy()
print(x_train.shape, y_train.shape)

adaline = AdalineGD()
adaline.fit(x_train, y_train)

df = pd.read_csv('inputpixels_testing.csv', header=None)
x_test, y_test = df.iloc[:, :-1].to_numpy(), df.iloc[:, -1].to_numpy()
print(x_test.shape, y_test.shape)

for i in range(x_test.shape[0]):
  # print(x_test[i])
  y_pred = adaline.predict(x_test[i])
  print(f'Actual: {y_test[i]}, predicted: {y_pred}')
  # print('Accuracy: %.3f' % accuracy_score(y_test[i], y_pred))

(21, 63) (21,)
(9, 63) (9,)
Actual: -1, predicted: -1
Actual: 1, predicted: 1
Actual: 1, predicted: 1
Actual: -1, predicted: 1
Actual: -1, predicted: 1
Actual: -1, predicted: 1
Actual: -1, predicted: 1
Actual: -1, predicted: 1
Actual: -1, predicted: 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:56: RuntimeWarning: overflow encountered in square